### PR TITLE
fix/test: t.Fatal should be called from `g` running the test or benchmark func

### PR DESCRIPTION
**Pull request by hitzhangjie**
The linter complains: the goroutine calls T.Fatal, which must be called in the same goroutine as the testSA2002(default).

testing.T.Fail will calls testing.common.FailNow(), this function will marks the test failing and call runtime.GoExit(). Sure, it could let the calling goroutine exit, but this is a misuse.

t.Fail should be used for marks the test failing and let the goroutine which runs this test or the benchmark func exit. So, just use t.Error+return instead.

### CODE REVIEW

**Comment by hitzhangjie** [comment]
It looks like the orignal code is not formatted as go conventions.
1. use 4 spaces -> uses 1 tab;
2. import uses `importPath` -> go uses "importPath"

Too many changes ... I will submit a small CL, instead.

**Comment by liuq19** [comment]
Thanks. Lots of changes now, welcome to submit a small CL ~

**Comment by AsterDY** [comment]
for format, sonic has its own style. If you want to change, you need change all the go files...

**Comment by hitzhangjie** [comment]
I have submit a small CL, without changing the format style.

**Review by liuq19 — APPROVED** [review]

**Comment by liuq19** [comment]
Thanks, LGTM

**Pull request merged**
